
server:
  port: 9001


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tomin;DB_CLOSE_DELAY=-1
    username: root
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true


springdoc:
  api-docs:
    version: openapi_3_0



